name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-cleaning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Databricks config file
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          DATABRICKS_WAREHOUSE_ID: ${{ secrets.DATABRICKS_WAREHOUSE_ID }}
          DATABRICKS_CATALOG: workspace
          DATABRICKS_SCHEMA: feature_store_project
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databricks/config
host = ${DATABRICKS_HOST}
token = ${DATABRICKS_TOKEN}
serverless = true
warehouse_id = ${DATABRICKS_WAREHOUSE_ID}
http_path = ${DATABRICKS_HTTP_PATH}
catalog = ${DATABRICKS_CATALOG}
schema = ${DATABRICKS_SCHEMA}
EOF

      - name: Run data cleaning script
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          DATABRICKS_WAREHOUSE_ID: ${{ secrets.DATABRICKS_WAREHOUSE_ID }}
          DATABRICKS_CATALOG: workspace
          DATABRICKS_SCHEMA: feature_store_project
        run: |
          python src/cleaning/data_cleaning.py
